"""
Main runner that uses Tournament from tournament.py without duplicating its logic.
This file intentionally makes minimal assumptions/changes to Tournament and
does not interfere with the Tournament class responsibilities.

Workflow:
1. Generate random dataset (both players RANDOM) into random storage dict.
2. Freeze a copy of the random storage dict and use it as lookup for greedy data generation.
3. Generate greedy dataset (X is GREEDY consulting the frozen random lookup) into greedy storage dict.
4. Evaluate deterministic greedy (epsilon=0) vs random using the greedy dictionary.
5. Sanity check: greedy with epsilon=1 should behave like random.
"""
import time
from copy import deepcopy

from tournament import Tournament  # uses the Tournament implementation from tournament.py

# --- configuration ---
N_RANDOM = 100_000      # number of games to generate random dataset
N_GREEDY = 100_000      # number of games to generate greedy dataset (greedy consults random_dict)
EVAL_GAMES = 1000       # number of evaluation games to compare greedy vs random
EPSILON_GREEDY = 0.1    # exploration probability used during greedy dataset generation
RANDOM_DICT_FILE = "states_random.json"
GREEDY_DICT_FILE = "states_greedy.json"


def print_stats(label, stats):
    total = sum(stats.values())
    print(f"=== {label} (total games={total}) ===")
    for k in ("VICTORY_X", "VICTORY_O", "TIE"):
        print(f"{k:10s}: {stats[k]:6d} ({stats[k]/total:.3%})")
    print()


def save_storage_dict_to_json(storage_dict, filename):
    # Tournament.save_dict already does a safe json dump, but we call it here as well for clarity.
    # storage_dict keys are expected to be strings produced by hash_board.
    import json
    with open(filename, "w") as f:
        json.dump(storage_dict, f)


def main():
    start_time = time.time()

    # 1) Generate random dataset
    print("1) Generating random dataset (both players RANDOM)...")
    t_random = Tournament(games=N_RANDOM, play_mode="RANDOM", epsilon=0.0,
                          lookup_dict=None, storage_dict={})
    t_random.run()
    print_stats("Random dataset stats", t_random.stats)
    t_random.save_dict(RANDOM_DICT_FILE)
    print(f"Saved random states dict to {RANDOM_DICT_FILE} (entries={len(t_random.storage_dict)})\n")

    # Freeze a copy of the random storage dict to use as a read-only lookup for greedy generation.
    # Use deepcopy to ensure no accidental sharing/mutation.
    random_lookup = deepcopy(t_random.storage_dict)

    # 2) Generate greedy dataset (X is GREEDY, consults random_lookup). Store into a fresh dict.
    print("2) Generating greedy dataset (X is GREEDY, consults random dataset for rankings)...")
    t_greedy = Tournament(games=N_GREEDY, play_mode="GREEDY", epsilon=EPSILON_GREEDY,
                          lookup_dict=random_lookup, storage_dict={})
    t_greedy.run()
    print_stats("Greedy dataset stats (games generated by greedy agent)", t_greedy.stats)
    t_greedy.save_dict(GREEDY_DICT_FILE)
    print(f"Saved greedy states dict to {GREEDY_DICT_FILE} (entries={len(t_greedy.storage_dict)})\n")

    # 3) Evaluate deterministic greedy (epsilon=0) vs random opponent, using greedy storage as lookup.
    print(f"3) Evaluating deterministic greedy agent (epsilon=0) for {EVAL_GAMES} games vs random opponent...")
    greedy_lookup_for_eval = deepcopy(t_greedy.storage_dict)
    t_eval = Tournament(games=EVAL_GAMES, play_mode="GREEDY", epsilon=0.0,
                        lookup_dict=greedy_lookup_for_eval, storage_dict={})
    t_eval.run()
    print_stats("Deterministic greedy (eval) stats", t_eval.stats)
    mean_unknown, _ = t_eval.unknown_stats()
    print(f"Average unknown_ratio during eval: {mean_unknown:.4f}\n")

    # 4) Sanity check: greedy with epsilon=1 should behave like random
    print(f"4) Sanity check: greedy agent with epsilon=1 (should behave randomly) for {EVAL_GAMES} games...")
    t_sanity = Tournament(games=EVAL_GAMES, play_mode="GREEDY", epsilon=1.0,
                          lookup_dict=random_lookup, storage_dict={})
    t_sanity.run()
    print_stats("Greedy(epsilon=1) stats", t_sanity.stats)
    mean_unknown_sanity, _ = t_sanity.unknown_stats()
    print(f"Average unknown_ratio during sanity check: {mean_unknown_sanity:.4f}\n")

    total_time = time.time() - start_time
    print(f"All done. Total elapsed time: {total_time:.1f}s")


if __name__ == "__main__":
    main()